### ISSUE TITLE
[FR] Add PlaylistManager to BeatMods to work with Mod Assistant

### ISSUE THREAD

**Issue by david-kalbermatten** [rithik-b/PlaylistManager#15]
I think the community would highly appreciate it if you were to add an entry for your mod on BeatMods and keep it up to date.
[https://beatmods.com/#/mods](https://beatmods.com/#/mods)

This way we could install and update it with [ModAssistant](https://github.com/Assistant/ModAssistant).

**Comment by rithik-b** [comment]
I did, currently pending approval from the BeatMods team so please be patient!
![E50B9992-67E1-40F7-BC17-C7DA0AD2AE87](https://user-images.githubusercontent.com/33881026/107961667-3621b400-6f74-11eb-9852-2c97a05c6591.jpeg)
