### ISSUE TITLE
Scroll through playlists?

### ISSUE THREAD

**Issue by francislavoie** [rithik-b/PlaylistManager#17]
I might be missing something obvious, but I don't see a way to scroll through the list of playlists. I can only see the first 6 playlists in the top-right, but I have plenty more than that from earlier versions of BeatSaber. When the playlists were bottom-rendered, there were `<` and `>` buttons to scroll through, but it seems like those are no longer around. 🤔

**Comment by rithik-b** [comment]
If you’re not using a valve index use the thumbstick
If you’re using a Valve Index, please read the readme to configure your button bindings so you can use the thumbstick 
Also the buttons are absent from the base game, however I am bringing the buttons back in a future version. In the meantime, use the stick to scroll.

**Comment by francislavoie** [comment]
Ah, thanks - I am using an Index.
