### ISSUE TITLE
Sort music by song alphabetically

### ISSUE THREAD

**Issue by nn3d** [rithik-b/PlaylistManager#20]
Hi,
I used the previous plugin Playlist lite and all the maps inside a playlist were list in alphabetical order. Could you add a new option so we can choose how to sort the maps (alphabetical or date).

Well done for this great plugin!

**Comment by rithik-b** [comment]
I would suggest using [SongBrowser](https://github.com/halsafar/BeatSaberSongBrowser) for getting various sorting and filtering options for Playlists. I've intentionally been showing playlists in the same order as the json for now and I'm trying not to duplicate the functionality of another existing mod, makes the mod easier to maintain!
