### ISSUE TITLE
Add Songs from playlist view to different playlist

### ISSUE THREAD

**Issue by AR15senalOfCode** [rithik-b/PlaylistManager#21]
Currently, if you have selected a song from a playlist, there is no option to add this song to another playlist.

Personally, I like to kind of categorize songs by using playlists. But when I find a good song that is inside a playlist, I would have to search for the name in the 'All Songs' view to be able to add it to another playlist.

Best regards

**Comment by rithik-b** [comment]
Thanks for the suggestion, good news this feature is already implemented for the next version bump of the plugin! There's a lot of changes with this upcoming major version change of the update so you might have to wait a bit, but I will link this issue with the PR of that branch so you can keep track of when it's out!
