### ISSUE TITLE
Show which playlists contain the selected song

### ISSUE THREAD

**Issue by AR15senalOfCode** [rithik-b/PlaylistManager#24]
It would be very useful to be able to see in which playlist(s) a certain song/beatmap is.

Just as a suggestion, you could show a list of containing playlists when hovering over the + Button (button to add song to a playlist). Or you could mark playlists containing the song in the UI where you choose which playlist to add the song to.

**Comment by rithik-b** [comment]
It already exists, after you add a song to a playlist you will see a (contains song) written next to the number of songs.
