### ISSUE TITLE
Removing a map from a playlist can "shift" the rest of the playlist

### ISSUE THREAD

**Issue by OoDeeR** [rithik-b/PlaylistManager#29]
What: If you remove a map from a playlist in game, there's a chance that the following element of the playlist get temporarily messed up. While the entry is gone, some of the references still point to it, such as:
-  after deleting an entry, if you go to the next entry and try to delete it, you're prompted to delete the just deleted entry again. This will not delete the entry you actually selected.
-  after deleting an entry, if you go to the next entry, if the deleted entry had a certain difficulty assigned, that difficulty will be wrongly displayed for the next playlist item.

Refreshing playlists via the mod panel fixes this, but the issue will reappear whenever you remove another entry.

Note: sometimes, removing an item seems to work just fine, so it might take 2 or 3 tries to reproduce this. Could be related to having specific difficulties assigned to an entry. I did not test that extensively, when in game.

**Comment by rithik-b** [comment]
Good catch, I've found exactly what causes this issue. I'll link a dll to this issue and if you cant repro with it then i will close the issue!

**Comment by rithik-b** [comment]
https://github.com/rithik-b/PlaylistManager/actions/runs/999671072
Try downloading it here, see if it works

**Comment by OoDeeR** [comment]
Seems to work as intended now. Thanks for the quick fix!

**Comment by rithik-b** [comment]
Sounds good I’ll merge this change in to an update soon
