### ISSUE TITLE
bug in playlist list

### ISSUE THREAD

**Issue by zivoy** [rithik-b/PlaylistManager#3]
On playlists that don't have a base64 image like the ones generated by BS-PP-BOOSTER mod or the old syncsaber mod. There is a white square that doesn't bend/stay on the same level as the other playlists.

PlaylistLoaderLite had a stock image that it would use in those cases.

**Comment by rithik-b** [comment]
You should redirect this bug to [BeatSaberPlaylistsLib](https://github.com/Zingabopp/BeatSaberPlaylistsLib) instead since that is handling the I/O (reading) of playlists files.
