### ISSUE TITLE
[Feature/Change Request] Update playlist without downloading all songs

### ISSUE THREAD

**Issue by ChrisJAllan** [rithik-b/PlaylistManager#32]
It would be nice to be able to update a mapper playlist without downloading all their maps. It could be a yes/no after updating or a config option, etc.

**Comment by rithik-b** [comment]
I'll do you one better, how about both?
https://github.com/rithik-b/PlaylistManager/commit/0c6c2ff0509f78d377764d8be5cf5dfd1a89708b

A setting that lets you choose between always download after sync, always not download after sync or ask each time. Should be in the next update coming today!

**Comment by ChrisJAllan** [comment]
Nice, thanks!
