### ISSUE TITLE
Issue when loading custom playlists

### ISSUE THREAD

**Issue by HeyItsJinx** [rithik-b/PlaylistManager#43]
When i hit download. It doesn't get added to queue, refreshes and says the exact same msg no matter which one out of the like 28 i have. it always says "291 songs" and "28 Playlists loaded" There is apparently no queue when i click download

this is in game.

**Comment by rithik-b** [comment]
Might be either beatsaver being down, your internet having issues or the songs in the playlist not being on beatsaver anymore. Can you post your log file here so I can check?

**Comment by HeyItsJinx** [comment]
> Might be either beatsaver being down, your internet having issues or the songs in the playlist not being on beatsaver anymore. Can you post your log file here so I can check?

sure. Is it "Latest Log"?

**Comment by rithik-b** [comment]
yes

**Comment by HeyItsJinx** [comment]
[_latest.log](https://github.com/rithik-b/PlaylistManager/files/7921962/_latest.log)

**Comment by rithik-b** [comment]
No playlist download was attempted in this session, can you please try to download a playlist, then close the game, then send latest.log?

**Comment by HeyItsJinx** [comment]
yes ill do that now i brb

**Comment by HeyItsJinx** [comment]
i just checked most recent in logs its the exact same.

When i click the playlist. no matter which one. I tried the sword art online pack. it says its been added to queue. shows me the exact same amount of songs i have and same amount of playlists, and nothing is ever in the queue despite it saying its been added.

**Comment by HeyItsJinx** [comment]
[_latest.log](https://github.com/rithik-b/PlaylistManager/files/7921974/_latest.log)
here it is in case its somehow different.

**Comment by HeyItsJinx** [comment]
ive just thought that i am using beatlist which i downloaded. that could be the problem. just clicked.

**Comment by rithik-b** [comment]
Hmm, not sure how beatlist would cause it. Maybe send me the playlist file of the playlist you were downloading? I tried the same pack from beatsaver myself and didnt experience any issues.

**Comment by HeyItsJinx** [comment]
its giving me it in the form of a JSON file is that meant to be like that?

**Comment by rithik-b** [comment]
yeah send it

**Comment by HeyItsJinx** [comment]
[Alphabeats-Monstercat-Music-Pack.txt](https://github.com/rithik-b/PlaylistManager/files/7922018/Alphabeats-Monstercat-Music-Pack.txt)
change the .txt to .JSON had to rename the type because github wouldn't recognise it

**Comment by rithik-b** [comment]
alright seems like it is a beatlist issue, the playlist is empty!
make sure to use MorePlaylists mod from ModAssistant to download playlists next time!

**Comment by HeyItsJinx** [comment]
ok no worries!
