### ISSUE TITLE
Unzipping Bug

### ISSUE THREAD

**Issue by Zingabopp** [rithik-b/PlaylistManager#44]
When unzipping, PlaylistManager goes through all entries and unzips the files to the song's base directory. If a song has an `autosaves` folder it will overwrite the good files with files from `autosaves`.

Example: https://na.cdn.beatsaver.com/b7da8742e3ef95126dc53a9209d2d15403ab0563.zip
`Info.dat` gets overwritten with an old version that lists the audio file as `thereal.ogg`

**Comment by Meivyn** [comment]
Following of https://github.com/Kylemc1413/SongCore/issues/79

**Comment by rithik-b** [comment]
It is the same for BeatSaverDownloader too, apparently it was done to protect from zip bombs
Do you know how to do about this without zip bombs?

**Comment by rithik-b** [comment]
https://github.com/Kylemc1413/BeatSaverDownloader/blob/23396cf5deb2a4629e9e2a27573e4949d14787da/BeatSaverDownloader/Misc/SongDownloader.cs#L105
Line in question

**Comment by Zingabopp** [comment]
i did this for mine:
```cs
foreach (ZipArchiveEntry? entry in zipArchive.Entries.OrderByDescending(e => e.Length))
                    {
                        if (!entry.FullName.Equals(entry.Name)) // If false, the entry is a directory or file nested in one
                            continue;```

**Comment by rithik-b** [comment]
Ah, simple fix! Thank you, I will fix this
