### ISSUE TITLE
Not adding Songs in the Playlist

### ISSUE THREAD

**Issue by ghost** [rithik-b/PlaylistManager#47]
Hey,

when adding a song to a created playlist its not adding the Song into it.
It creates the bplist file but the size of it is still 0KB.

Cinema Playlist gets imported and it can download the songs showing them and refreshes only when i create an own
one.

I run the latest version from github and beatsaversharp from auros the latest available from git. Same for the PlaylistLib.

Maybe its just an bug on my end but wanted to post it.

thanks alot

with best regards

LPDaVinci

**Comment by rithik-b** [comment]
Can you please try to add a song to a playlist again, then close the game and post the latest log from the logs folder?

**Comment by ghost** [comment]
This is a fresh created log file and i try to add a song to my anime playlist.

[_latest.log](https://github.com/rithik-b/PlaylistManager/files/8298262/_latest.log)

**Comment by rithik-b** [comment]
https://github.com/Zingabopp/BeatSaberPlaylistsLib/commit/567f64a0dc58505876b2f1cd063109b7583162bd
Thanks for the report, a fix should be out soon

**Comment by rithik-b** [comment]
https://github.com/rithik-b/PlaylistManager/releases/tag/1.6.4 here it is
