### ISSUE TITLE
Bug: Cannot add vanilla maps to most playlists

### ISSUE THREAD

**Issue by Undeceiver** [rithik-b/PlaylistManager#50]
This used to work in the past, and the vanilla maps (from OST or map packs) that I added to lists back in the day are still there and working fine. However, when I try to add them now, most of the time it won't work.

In particular, game will say "Successfully added map to playlist", but it will not be in the playlist. In fact, all my playlists are no duplicates, so normally when you add a map to them, the list disappears from the list of playlists that you can add the map to. Right now, with vanilla maps, it does not disappear (so the mod seems aware that it was not added).

I've had it work on some specific playlists. I looked on the files of those playlists to compare with the others and found no difference. It seems relatively random.

Adding custom maps to any playlists seems to work fine every time.

This is version 1.22 of Beat Saber, and most up-to-date playlistmanager version according to modassistant at the time of this message (in particular, 1.6.5).

Feel free to reach out to me if you cannot reproduce it or need additional information. Undeceiver#3265 on Discord.

**Comment by Meivyn** [comment]
Fixed by https://github.com/Zingabopp/BeatSaberPlaylistsLib/pull/38/commits/3b404e0f4f65b67b65aa9ee0a98e00aa1fe5b686.
