### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by TABURELTER** [rithik-b/PlaylistManager#55]
Hello, I have a problem with the IPA: 

Restoring Beat Saber_Data\Managed\System.Runtime.Serialization.dll
  D:\Folder game\Beat Saber\Beat Saber\IPA\Backups\Beat Saber\2022-10-05_3-51-00\Beat Saber_Data\Managed\System.Runtime.Serialization.dll => D:\Folder game\Beat Saber\Beat Saber\Beat Saber_Data\Managed\System.Runtime.Serialization.dll
ERROR: Oops! This should not have happened.

System.UnauthorizedAccessException: Access denied via path"D:\Folder game\Beat Saber\Beat Saber\Beat Saber_Data\Managed\System.Runtime.Serialization.dll".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   в System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   в IPA.Patcher.BackupUnit.Restore()
   в IPA.Patcher.BackupManager.Restore(PatchContext context)
   в IPA.Program.Install(PatchContext context)
[Press any key to continue]

**Comment by TABURELTER** [comment]
> Hello, I have a problem with the IPA:
> 
> Restoring Beat Saber_Data\Managed\System.Runtime.Serialization.dll D:\Folder game\Beat Saber\Beat Saber\IPA\Backups\Beat Saber\2022-10-05_3-51-00\Beat Saber_Data\Managed\System.Runtime.Serialization.dll => D:\Folder game\Beat Saber\Beat Saber\Beat Saber_Data\Managed\System.Runtime.Serialization.dll ERROR: Oops! This should not have happened.
> 
> System.UnauthorizedAccessException: Access denied via path"D:\Folder game\Beat Saber\Beat Saber\Beat Saber_Data\Managed\System.Runtime.Serialization.dll". в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) в System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost) в System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite) в IPA.Patcher.BackupUnit.Restore() в IPA.Patcher.BackupManager.Restore(PatchContext context) в IPA.Program.Install(PatchContext context) [Press any key to continue]

PS. Running as an administrator does not help

**Comment by rithik-b** [comment]
IPA issue
