### ISSUE TITLE
Possible bug: Not all playlists showing when adding songs to another playlist, deleting cover images, or changing a cover image for a playlist in game (recordings of issue attached)

### ISSUE THREAD

**Issue by ariJayne** [rithik-b/PlaylistManager#56]
Hi, not sure if this is the right place for this but figured I'd post the issue here as well since your repo is credited in [ this repo ](https://github.com/Metalit/PlaylistManager) which is where the questboard link originally took me.. 
![image](https://user-images.githubusercontent.com/38627863/202936033-2cba6fc7-ca06-4beb-b759-a4f01d8d84ea.png)

[Here's a link to the original issue](https://github.com/Metalit/PlaylistManager/issues/4) I posted as well as what's pasted below - I'm currently on beat saber version 1.25.1. **Please let me know if there's any more information I can provide if needed!** 

> I posted this in the quest-help channel in discord but re-posting here since this does seem like a bug (and no one had an answer there)
> 
> When I'm trying to move songs to other playlists it is only possible if I have the playlist set in one of the first 4-5 spots, if it's any farther in the list it doesn't show on the menu which makes it super inconvenient to quickly sort and move songs around. It also does this when deleting cover images in mod settings or changing a cover image (whatever fits in the first section is all you'll be able to see)

https://user-images.githubusercontent.com/38627863/202936188-a08e3863-1c5e-4874-a491-1bac2ee1edc8.mp4

https://user-images.githubusercontent.com/38627863/202936189-e1967d01-ec5f-4bd8-b00e-5425d8b65f58.mp4

**Comment by rithik-b** [comment]
This is the quest version which isn't a part of this repo, please open an issue [here](https://github.com/Metalit/PlaylistManager)
