### ISSUE TITLE
Add to Playlist menu not showing anything past the first page

### ISSUE THREAD

**Issue by wisnoskij** [rithik-b/PlaylistManager#57]
I have a brand new BSMG installation with all defaults I think. But when I go to add a song to a playlist, only  the first page (5-sh items) show up. For a short while I think I had 1-2 items in the second page, but after I made 1 more playlist they all disappeared.

My Setup:
Quest 2
Beatsaber 1.25.1
BSMG 1.16.0
PlaylistManager v1.2.0

BSMG 1.16.0 seems to come with
SongLoader v0.10.9
PinkCore v1.8.3
PlaylistManager v1.2.0
SongDownloader v0.5.0
datakeeper v0.1.2
PlaylistCare v1.1.0
ModList v0.1.7
libquestui.so
libtinyxml2.so
libpaperlog.so
libcodegen.so
libbsml.so
libbeatsaber-hook_3_14_0.so
libcustom-types.so

**Comment by rithik-b** [comment]
This is the quest version which isn't a part of this repo, please open an issue [here](https://github.com/Metalit/PlaylistManager)
