### ISSUE TITLE
Highlighted difficulty labels don't reset their color when changing selection

### ISSUE THREAD

**Issue by qqrz997** [rithik-b/PlaylistManager#70]
beatmaps with multiple difficulties will show multiple highlighted difficulties even when they aren't supposed to if you select other maps with other highlighted difficulties. the bug is persistent through the play session up until restart or internal restart.

**Comment by Meivyn** [comment]
Fixed in https://github.com/rithik-b/PlaylistManager/commit/2ec200820c0d7f2031e8d6093c3542ef46024f71.

**Comment by spacky1** [comment]
are you planning to backport this fix to older versions? (1.37.1/1.37.2)

**Comment by Meivyn** [comment]
I don't backport anything unless it is absolutely necessary. I don't want to encourage people to stay on downgraded versions.
