### ISSUE TITLE
(1.37) Difficulty does not show up correctly in game

### ISSUE THREAD

**Issue by HalloTheEngineer** [rithik-b/PlaylistManager#73]
The "old" [difficulties](https://github.com/rithik-b/PlaylistManager/wiki/Difficulties) that could be set in the playlist file don't show up correctly in the game any more. Instead, all _difficulties_ of a map are highlighted, independent on the _characteristic_.
If this is a bug that appears only on my side, I'm sorry for creating the issue.
![image](https://github.com/user-attachments/assets/e186b061-1aca-4d33-9790-2d44857636f2)
![image](https://github.com/user-attachments/assets/94ac778e-70a8-46c4-af22-68a51a7aba88)
![image](https://github.com/user-attachments/assets/09d707b5-9693-4e3f-aa17-455b84a69e06)

**Comment by Meivyn** [comment]
This should be fixed already in v1.7.2.

**Comment by HalloTheEngineer** [comment]
Where can I find the compiled mod? Could you add a release with the updated mod? Thanks in advance.

**Comment by Meivyn** [comment]
The release is available for version 1.37.3+ only, I am not making backports.

**Comment by HalloTheEngineer** [comment]
Alright. But where can I find the newest release? According to GitHub, the latest release is version 1.6.6. Is there another Repository?

**Comment by Meivyn** [comment]
On whatever [mod installer](https://bsmg.wiki/pc-modding.html#installers) you are using.
