### ISSUE TITLE
playlist mod broken?

### ISSUE THREAD

**Issue by Midnightcotto** [rithik-b/PlaylistManager#75]
uh heres this idk how to fix it
https://medal.tv/games/beat-saber/clips/iPLlOKsRN2UodVF8W/d1337FK8tAt3?invite=cr-MSxzUmEsMjA1NDY5MzM3LA

**Comment by Meivyn** [comment]
You fix it by using less playlist. I am aware of that issue, but I ignored it since it requires an astronomical amount of playlists, which would break the UI anyway at some point.
